language: python
python:
  - "2.7"
# HTSeq is not compatible with python3
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "nightly"
# command to install dependencies
install:
  - sudo apt-get install python-numpy
  - sudo pip install HTSeq
  - sudo python setup.py install

script:
  - nosetests -v tests/*.py

notifications:
  email: false
