language: python
python:
  - "2.7"
# HTSeq is not compatible with python3
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "nightly"
# command to install dependencies
install:
  - "virtualenv -p python2 .venv ; source .venv/bin/activate ; apt-get install python-numpy ; pip install HTSeq ; python setup.py install"

script:
  - "source .venv/bin/activate ; nosetests -v tests/*.py"

notifications:
  email: false
